'use client'
import { useEffect, useState } from 'react'
import api from '@/lib/api'
import Link from 'next/link'
import OSShell from '@/components/os/OSShell'
import { useAuth } from '@/lib/auth'

export default function ReportsPage() {
  const { user } = useAuth()
  const [reports, setReports] = useState<any[]>([])
  const [loaded, setLoaded] = useState(false)

  // A report is generated by a background worker, so a freshly requested one shows
  // "Analyzing…" until it lands. Poll while any is still pending so the list flips to
  // Ready on its own (basketball reports can take a few minutes).
  const anyPending = reports.some(r => (r.status ? r.status === 'generating' : !r.generated_at))

  useEffect(() => {
    if (!user) return
    api.get('/reports').then(r => setReports(r.data || [])).catch(() => {}).finally(() => setLoaded(true))
  }, [user])

  useEffect(() => {
    if (!user || !anyPending) return
    const t = setInterval(() => {
      api.get('/reports').then(r => setReports(r.data || [])).catch(() => {})
    }, 5000)
    return () => clearInterval(t)
  }, [user, anyPending])

  return (
    <OSShell title="Scout Reports">
      <div className="sec-hdr"><div className="sec-title">📋 Scout Reports</div></div>
      <div className="rpt-list">
        {reports.map(r => (
          <Link key={r.id} href={`/reports/${r.id}`} style={{ textDecoration: 'none' }}>
            <div className="rpt-row">
              <div className="rpt-icon">{r.report_type === 'self_scout' ? '🪞' : '📋'}</div>
              <div className="rpt-info">
                <div className="rpt-name">{r.title}</div>
                <div className="rpt-meta" style={{ textTransform: 'capitalize' }}>{r.sport} · {String(r.report_type || 'opponent').replace('_', ' ')}</div>
              </div>
              {r.watermarked && <span className="tag tw">Trial</span>}
              {r.status === 'failed'
                ? <span className="tag" style={{ background: 'rgba(224,112,112,0.15)', color: '#e07070' }}>Failed</span>
                : r.generated_at
                  ? <span className="tag tg">Ready</span>
                  : <span className="tag tgo">Analyzing…</span>}
            </div>
          </Link>
        ))}
        {loaded && reports.length === 0 && (
          <div className="ai-box" style={{ textAlign: 'center' }}>
            No reports yet. Tag plays on a game film and generate an AI scout report, or{' '}
            <Link href="/scout" style={{ color: 'var(--green3)' }}>start a scout →</Link>
          </div>
        )}
      </div>
      <div className="powered">Powered by <a href="https://cosbyaisolutions.com" target="_blank" rel="noreferrer">Cosby AI Solutions</a></div>
    </OSShell>
  )
}
